<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="../../vendor/twbs/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../vendor/twbs/bootstrap/dist/js/bootstrap.js">
    <link rel="stylesheet" href="css/main.css">
    <title>Home</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron mt-4">
            <h1 class="display-4">
                <img class="logo"  src="image/logo.jpeg" alt="">
                Dev Salsa
            </h1>
            <p class="lead">
                Hola, soy <span class="text-primary" >Alejandro Diaz</span> 
                <br> 
                Esta es mi prueba y espero que sea de su agrado , tambien agrego mi <a class="btn btn-link" href="document/cv.pdf" target="_blank" rel="noopener noreferrer">CV</a> para mayor información
            </p>
            <hr class="my-4">
            <p>
                Siga la siguient instrucciones para disfrutar de las funcionalidades de esta prueba
                <h6><b>Instrucciones</b></h6>
                <ul>
                    <li>Ingrese a esta <a href="index.php?c=init">aqui</a> para inicializar la base de datos de la prueba</li>
                    <li>Ingrese en la opcion de <b>Nuevo usuario</b></li>
                    <li>Ingrese en la opcion de <b>Acceder</b></li>
                    <li><b>Gracias :)</b></li>
                </ul>    
            </p>
            
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="index.php?r=login" role="button">Acceder</a>
                <a class="btn btn-primary btn-lg" href="index.php?r=register" role="button">Nuevo usuario</a>
            </p>
        </div>
    </div>
</body>

</html>