<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="../../vendor/twbs/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="../../vendor/twbs/bootstrap/dist/js/bootstrap.js">
    <link rel="stylesheet" href="css/main.css">
    <title>Acceder</title>
</head>

<body>
    <div class="container">
        
    </div>
</body>

</html>